# Generated by Django 5.2.6 on 2025-09-22 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slider_per_page",
                    models.PositiveIntegerField(
                        default=3,
                        help_text="Number of slides to show at once on desktop.",
                    ),
                ),
                (
                    "slider_per_move",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Number of slides to move when a user clicks next/prev.",
                    ),
                ),
                (
                    "slider_gap",
                    models.CharField(
                        default="1rem",
                        help_text="Gap between slides (e.g., '1rem', '20px').",
                        max_length=10,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Site Settings",
            },
        ),
    ]
